services:
  client:
    build: ./client/
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build: ./api/
    expose:
      - 8080
    ports:
      - "8080:8080"
networks:
  default:
    name: compressor_network
